### ISSUE TITLE
Support bindings by indexing

### ISSUE THREAD

**Issue by Matt-Esch** [Raynos/jsonml-stringify#12]
I think we need to treat attributes and children separately. We should define plugins for children and plugins for attributes.
- Some attributes may be functions. The biggest use case we have for this is bindings into the attribute values. What I would like to be able to do here is define a function for the attribute context and a function for the child context. 

``` js
["div", {
    className: { "if": ["model.visible", "visible" : "" ] }
}, [{ "format": [
    "Hello {0}, how are you",
    { "bind": "model.name" }
]}]

// -> normalize(tree, opts)

["div", {
    "className": "visible",
    "data-bindindex": 0
}, [["span.binding", {
    "data-bindindex": 1
}, "Hello Jake, how are you?"]]
```

To outline what happens here:
- The className property resolves to the computed binding. So this implies that when we call normalize, the data is needed.
- data-bindindex is added to the properties. We can assume that bindings are seen in the same order on both the client and the server, so we use this number to indicate which binding should be used. Running the template again on the client should produce the same binding table, allowing us to tie up the dom with the bindings without having to worry about potential mutations or matching a jsonml tree to a dom tree.
- I turned the dynamic text node into a span and added a "binding" class to it. This could be nice when visualizing

**Comment by Raynos** [comment]
> I think we need to treat attributes and children separately. We should define plugins for children and plugins for attributes.

They are already seperate

``` ocaml
type Plugin := {
    stringify: (JsonML, JsonMLOptions) => String,
    dom: (JsonML, JsonMLOptions) => DOMElement,
    merge: (JsonML, JsonMLMergeOptions) => void,
    type: String,
    normalize: (JsonML, JsonMLOptions) => JsonML,
    renderProperty: (DOMElement, value: Any, key: String, JsonMLOptions),
    renderStyle: (DOMElement, value: Any, key: String, JsonMLOptions),
    stringifyProperty: (value: Any, key: String, JsonMLOptions) => String,
    mergeProperty: (DOMElement, value: Any, key: String, JsonMLMergeOptions),
    setProperty: (value: Any, key: String),
    getProperty: (value: Any, key: String) => String
}
```

 a primitive is a unique identifier preferably tied to the unique identifier used in npm as `jsonml-<identifier>` to avoid name collisions.

For any new primitive you define the rendering / stringify / blargh algorithm for children, properties & styles.

**Comment by Raynos** [comment]
> Some attributes may be functions. The biggest use case we have for this is bindings into the attribute values.

I have no idea what you mean.

However that `if` thing you have can be implemented as is. You return a string for stringifyProperty & can return multiple attributes.

For `format` you can obvouisly return whatever child you want so that can also already be done.

**Comment by Raynos** [comment]
> The className property resolves to the computed binding. So this implies that when we call normalize, the data is needed.

The world `normalize` means a very _specific_ thing currently. Specifically it takes any node in a jsonml tree and simplifies it to a simpler form. It's like static macro expansion.

It's currently used for the thing that turns `"Hello"` into `["#text", {}, "Hello"]` and other normalization of loose representation of JsonML into the strict representation.

Currently `normalize` allows you to normalize the entire tree and not just normalize a local plugin node by replacing it with another node. `normalize` can rewrite the entire tree if it wants too.

**Comment by Raynos** [comment]
> data-bindindex is added to the properties. We can assume that bindings are seen in the same order on both the client and the server, so we use this number to indicate which binding should be used. Running the template again on the client should produce the same binding table, allowing us to tie up the dom with the bindings without having to worry about potential mutations or matching a jsonml tree to a dom tree.

I presume `data-bindindex` is an implementation detail of a `merge` friendly `stringify` function designed for implementing `merge` without edge cases. 

This may or may not be needed. If it's necessary to implement `merge` correctly _and_ if `merge` with this is significantly faster then alternatives then it's worth doing. 

I'm not sure whether this should go in `stringify` or `merge-stringify` 

This raises another point. The idea that we really should have a seperate git repo for `stringify`, `merge`, `dom` & pals. And have a way to share a bunch of the common code like the strict JsonML definition & the plugin mechanisms.

This basically means that `jsonml-stringify` & `jsonml-dom` will dogfood `jsonml-core`. The main advantage is a strong example and a low barrier to entry for other people to implement say `jsonml-databind-merge` & `jsonml-databind-stringify` without having to effectively fork the jsonml stuff. It should be easy to contribute new tree rendering strategies
