### ISSUE TITLE
observable computations

### ISSUE THREAD

**Issue by Matt-Esch** [Raynos/jsonml-stringify#8]
Are we going to remove all computation from observable jsonml structures? - naturally we write things like

``` js
["input", {
    type: "checkbox",
    checked: model.emailUpdates ? "checked" : false
}]
```

I think this inline computation is useful because it's producing dom-specific representations of the view which we logically think about in some other way. Would something like this work?

``` js
["input", {
    type: "checkbox",
    checked: computed([model.emailUpdates], function(updates) {
         return updates ? "checked" : false
    })
}]
```

of course this is a bad example because the checked attribute must be fully removed

**Comment by Raynos** [comment]
One option is to have

``` js
["input", {
    type: "checkbox",
    checked: model.emailChecked
}]
```

Another option is to have 

``` js
["input", {
    type: "checkbox",
    checked: computed([model.emailUpdates], function(updates) {
         return updates ? "checked" : ""
    })
}]
```

I think it's fine to have computed properties for text content and properties. i.e. the latter

One place where computed properties become dangerous is 

``` js
computed([foo], function (foo) {
  return foo ? ["ol", ...] : ["ul", ... ]
}
```

**Comment by Raynos** [comment]
This can be changed to be declarative

``` js
module.exports = template

function template(model) {
    return ["form", [
        checkbox("istrue", model.isTrue)
    ]]
}

function checkbox(name, selected) {
    return ["input", {
        type: "checkbox",
        name: name,
        selected: selected ? "selected" : null
    }]
}
```

Since it's a ternary the `either` plugin allows you to express this in a reactive fashion

``` js
module.exports = template

function template(model) {
    return ["form", [
        checkbox("istrue", model.isTrue)
    ]]
}

function checkbox(name, selected) {
    return ["input", {
        type: "checkbox",
        name: name,
        selected: either(selected, "selected", null)
    }]
}
```

**Comment by Raynos** [comment]
Of course this is a bad example. jsonml supports boolean properties. You shouldn't set it to `"selected"` you should just set it to `true` or `false`

``` js
module.exports = template

function template(model) {
    return ["form", [
        checkbox("istrue", model.isTrue)
    ]]
}


function checkbox(name, selected) {
    return ["input", {
        type: "checkbox",
        name: name,
        selected: selected
    }]
}
```

**Comment by Raynos** [comment]
Boolean properties are a solved problem.

We should create a new issue with better use cases.
