### ISSUE TITLE
jsonml should not contain functions as nodes

### ISSUE THREAD

**Issue by Matt-Esch** [Raynos/jsonml-stringify#9]
jsonml stringifying should be based on static structures. There are a few good reasons for this
- You can hide state inside functions, which can lead to nasty side effects
- You cannot transfer functions reliably down the wire due to closure scope
- Static analysis of the tree is far nicer/easier if you keep the logical representation in-tact rather than composing it immediately into jsonml
- You don't hard couple to an implementation of any given sub-component in the jsonml tree, allowing for configuration of types at runtime (consider themed elements with slightly different structures without having massive if/switch statements in one template file).
- You can, if you so wish, use functions to compute a structure, but that result itself is a static json structure. For example, you can compose a page using multiple widgets by calling the widget functions returning their placeholders, but the structure i.e. widget placement is then static. You returned a page representation in a static form using normal javascript to produce that output.
- Static structures are explicit and easier to reason about. Strictness will reduce sources of errors.

The major reason motivating this is to dissuade the use of functions in templates, which decreases the likelihood that users experience bad side-effects. Arguably building static structures is "less expressive" - you can't use full javascript to do dynamic rendering, but the arguments that apply to functional reactive programming (in particular the argument for building static reactive trees) applies here also. With a static structure you have to encode upfront all of the dynamic portions of the template - definitely easier to reason about.

For all reasonable use cases of functions in jsonml, a function call can be represented by an explicit json structure. They are equivalent. 

For example

``` js
["ol", [
    list(model.zs, function (value) {
        return ["li", [
            ["span", "item"],
            ["span", value]
        ]]
    })
]]
```

Can be described equivalently in a static structure:

``` js
["ol", {
    "list": {
        "model": "zs",
        "template": ["li", [
            ["span", "item"],
            ["span", { "model": true }]
        ]]
    }
}]
```

But unlike the static case, the user is lead to believe that arbitrary mutation is allowed/possible, for example 

``` js
["ol", [
    list(model.option, function (value) {
        model.index += 1

        return ["li", [
            ["span", "item"],
            ["span", [value, index].join(" ")]
        ]]
    })
]]
```

**Comment by Raynos** [comment]
What about `{ type: "computed", values: [ ... ], map: function (...) { ... } }`

how do you represent that without functions?

Also

``` js
// ugly
["ol", list("zs", ["li", [
  ["span", "item"],
  ["span", { model: "this" }]
]])]
```

``` js
// pretty
["ol", list(model.zs, function (value) {
  return ["li", [
    ["span", "item"],
    ["span", value]
  ]]
})]
```

The FRP comparison is void

> but the arguments that apply to functional reactive programming (in particular the argument for building static reactive trees)

FRP has a static tree of signals. The relationship between a signal and its parent is expressed as a function not as a string. If you try expressing frp using only strings you dont get far.

**Comment by Matt-Esch** [comment]
Only if you actually think the first one is prettier (subjective). As I said, nothing stops you from using functions that produce fixed structures without losing the introspective quality. Yours might actually be producing raw jsonml itself, which I would consider static. The jsonml renderer doesn't have to call a function for you.

``` js
["ol", [
    list("zs", ["li", [
        ["span", "item"],
        ["span", value]
    ]])
]]
```

Is identical to

``` js
["ol", {
    "list": {
        "model": "zs",
        "template": ["li", [
            ["span", "item"],
            ["span", { "model": true }]
        ]]
    }
}]
```

But subtle difference is that view models should be applied to static structures only. You should not be rendering a view model whilst producing the jsonml structure at the same time.

You would call the template containing functions just once on initialization, producing the static representation but allowing you to use something you consider "pretty".

The FRP comparison isn't void. It's not about strings vs functions, it's about static code paths vs dynamic on the fly code paths. Static structures are inherently easier to reason about, which is why static trees of data in FRP are nice; you can understand how they behave.

**Comment by Raynos** [comment]
FPR comparison is void because its safe to embed functions because they are always pure & typed.

**Comment by Matt-Esch** [comment]
I am cool with functions in jsonml if they are pure and typed because they are string serializable and have none of the caveats mentioned so consider the comparison valid. We just don't have enforced pure typed functions in js.
